# Generated by Django 5.1.1 on 2024-10-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS btree_gist;",
        ),

        migrations.RunSQL(
            """
            ALTER TABLE api_productpricing
            ADD CONSTRAINT unique_price_in_interval EXCLUDE USING gist (
                product_id WITH =,
                currency_id WITH =,
                tstzrange(
                    to_timestamp(from_date), 
                    to_timestamp(to_date), 
                    '[]'
                ) WITH &&
            )
            WHERE (deleted_at IS NULL);
            """,
            reverse_sql="""
            ALTER TABLE api_productpricing
            DROP CONSTRAINT IF EXISTS unique_price_in_interval;
            """
        ),

        migrations.RunSQL(
            """
            ALTER TABLE api_subscription
            ADD CONSTRAINT unique_subscription_in_interval EXCLUDE USING gist (
                customer_id WITH =,
                tstzrange(
                    to_timestamp(starts_at), 
                    to_timestamp(ends_at), 
                    '[]'
                ) WITH &&
            )
            WHERE (deleted_at IS NULL AND status = 'ACTIVE');
            """,
            reverse_sql="""
            ALTER TABLE api_subscription
            DROP CONSTRAINT IF EXISTS unique_subscription_in_interval;
            """
        ),
    ]
