# Generated by Django 5.1.1 on 2024-10-15 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241009_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='due_at',
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider_session_or_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('deleted_at', models.BigIntegerField(blank=True, null=True)),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_plan', to='api.plan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_plan', to='api.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_plan', 'to_plan'), name='unique_plan_pair')],
            },
        ),
    ]
