# Generated by Django 5.1.1 on 2024-10-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_due_date_invoice_due_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='deleted_at',
        ),
    ]
